# Generated by Django 4.0.6 on 2026-09-12 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corridor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('start_station', models.CharField(max_length=100)),
                ('end_station', models.CharField(max_length=100)),
                ('start_km', models.FloatField(default=0.0)),
                ('end_km', models.FloatField(default=100.0)),
                ('line_type', models.CharField(choices=[('SINGLE', 'Single Line'), ('DOUBLE', 'Double Line (UP/DN)'), ('TRIPLE', '3rd Line Added'), ('QUAD', 'Quadruple (4 Lines)')], default='DOUBLE', max_length=15)),
                ('is_electrified', models.BooleanField(default=True)),
                ('max_permissible_speed', models.IntegerField(default=130, help_text='km/h')),
                ('gmt', models.FloatField(default=35.0, help_text='Gross Million Tonnes per Annum')),
                ('daily_trains', models.IntegerField(default=120, help_text='Average daily trains (COA)')),
                ('corridor_window_start', models.TimeField(default='01:00:00', help_text='Typical COA low-traffic slot start')),
                ('corridor_window_end', models.TimeField(default='04:30:00', help_text='Typical COA low-traffic slot end')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=15)),
                ('train_name', models.CharField(max_length=120)),
                ('train_type', models.CharField(choices=[('VANDE_BHARAT', 'Vande Bharat / Premium SF'), ('RAJDHANI', 'Rajdhani / Tejas Express'), ('SHATABDI', 'Shatabdi Express'), ('MAIL_EXPRESS', 'Superfast / Mail Express'), ('PASSENGER', 'Passenger / MEMU Local'), ('GOODS_SCHEDULED', 'Scheduled Freight Corridor')], default='MAIL_EXPRESS', max_length=20)),
                ('direction', models.CharField(choices=[('UP', 'UP Line (Towards HQ/Delhi)'), ('DN', 'DOWN Line'), ('BOTH', 'Bidirectional')], default='UP', max_length=10)),
                ('entry_time', models.TimeField(help_text='Time entering corridor section')),
                ('exit_time', models.TimeField(help_text='Time clearing corridor section')),
                ('priority', models.IntegerField(choices=[(1, 'Priority 1 - Zero Detention (Rajdhani/Vande Bharat)'), (2, 'Priority 2 - Superfast Express'), (3, 'Priority 3 - Mail / Regular Express'), (4, 'Priority 4 - Suburban / Passenger'), (5, 'Priority 5 - Goods / Freight Traffic')], default=3)),
                ('days_of_run', models.CharField(default='Daily', max_length=50)),
                ('corridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_schedules', to='core_rail.corridor')),
            ],
            options={
                'ordering': ['entry_time'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('km_post', models.FloatField()),
                ('has_loop_lines', models.BooleanField(default=True)),
                ('loop_line_count', models.IntegerField(default=2)),
                ('corridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='core_rail.corridor')),
            ],
            options={
                'ordering': ['km_post'],
            },
        ),
        migrations.CreateModel(
            name='GoodsForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rake_id', models.CharField(max_length=30, unique=True)),
                ('commodity', models.CharField(choices=[('COAL', 'Coal / Thermal Power Rake'), ('CONTAINER', 'Container / CONCOR Fast Freight'), ('PETROLEUM', 'POL Tankers'), ('CEMENT', 'Cement / Clinker'), ('FOODGRAIN', 'Foodgrains / FCI Rake'), ('FERTILIZER', 'Fertilizers'), ('EMPTY_RAKE', 'Empty Wagon Repositioning')], default='COAL', max_length=20)),
                ('direction', models.CharField(choices=[('UP', 'UP Line'), ('DN', 'DOWN Line')], default='UP', max_length=10)),
                ('forecast_date', models.DateField()),
                ('target_window_start', models.TimeField()),
                ('target_window_end', models.TimeField()),
                ('can_be_regulated', models.BooleanField(default=True, help_text='Can wait in loop siding during block')),
                ('tonnage', models.IntegerField(default=3500, help_text='Trailing load in Metric Tonnes')),
                ('corridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_forecasts', to='core_rail.corridor')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='core_rail.zone')),
            ],
        ),
        migrations.AddField(
            model_name='corridor',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridors', to='core_rail.division'),
        ),
    ]
