# Generated by Django 4.0.6 on 2026-09-12 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_rail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('TMS', 'Engineering (Track / P-Way)'), ('SMMS', 'Signalling & Telecom (S&T)'), ('TDMS', 'Electrical / TRD (Traction OHE)'), ('COA', 'Control Office / Operating (COA)'), ('ADMIN', 'Chief Controller / Admin')], default='TMS', max_length=10)),
                ('designation', models.CharField(default='Senior Section Engineer', max_length=100)),
                ('employee_id', models.CharField(blank=True, max_length=30, null=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_rail.division')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
