# Generated by Django 4.0.6 on 2026-09-12 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_rail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=30, unique=True)),
                ('machine_name', models.CharField(max_length=100)),
                ('machine_type', models.CharField(choices=[('CSM', 'Continuous Action Tamper (CSM)'), ('DUOMAT', 'Plain Track Tamper (Duomat)'), ('BCM', 'Ballast Cleaning Machine (BCM)'), ('UNIMAT', 'Point & Crossing Tamper (Unimat)'), ('RGM', 'Rail Grinding Machine (RGM)'), ('TOWER_WAGON', '8-Wheeler TRD Tower Wagon (OHE)'), ('WIRING_TRAIN', 'OHE Wiring Special Train')], max_length=20)),
                ('department', models.CharField(choices=[('TMS', 'Engineering (Track)'), ('TDMS', 'Electrical (TRD / OHE)'), ('SMMS', 'S&T (Signal & Telecom)')], max_length=10)),
                ('base_depot', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('maintenance_due_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_id', models.CharField(max_length=40, unique=True)),
                ('source_system', models.CharField(choices=[('TMS', 'TMS (Track Management System - Engineering)'), ('SMMS', 'SMMS (Signal Maintenance & Management - S&T)'), ('TDMS', 'TDMS (Traction Distribution - Electrical/TRD)')], max_length=10)),
                ('track_line', models.CharField(choices=[('UP', 'UP Line'), ('DN', 'DOWN Line'), ('BOTH', 'Both Lines / Crossover'), ('YARD', 'Yard / Loop Lines')], default='UP', max_length=10)),
                ('km_start', models.FloatField()),
                ('km_end', models.FloatField()),
                ('activity_name', models.CharField(max_length=150)),
                ('activity_code', models.CharField(blank=True, max_length=50)),
                ('defect_description', models.TextField()),
                ('criticality', models.CharField(choices=[('EMERGENCY', 'Category 1: Emergency Defect / Immediate Risk'), ('URGENT_I', 'Category 2: Urgent / Overdue / Safety Impact'), ('NORMAL_II', 'Category 3: Cyclic Maintenance Due'), ('ROUTINE_III', 'Category 4: Routine Preventive / Inspection')], default='NORMAL_II', max_length=20)),
                ('duration_hours', models.FloatField(default=3.0, help_text='Required block duration in hours')),
                ('requires_power_block', models.BooleanField(default=False, help_text='Needs OHE 25kV traction power shutdown')),
                ('requires_traffic_block', models.BooleanField(default=True, help_text='Needs rail line closure')),
                ('speed_restriction_imposed', models.BooleanField(default=False, help_text='Temporary Speed Restriction (TSR) already active')),
                ('speed_restriction_kmh', models.IntegerField(blank=True, help_text='Current TSR limit, e.g. 30 km/h', null=True)),
                ('due_date', models.DateField()),
                ('overdue_days', models.IntegerField(default=0)),
                ('manpower_required', models.IntegerField(default=15, help_text='Number of staff / gang strength')),
                ('ai_priority_score', models.FloatField(default=50.0, help_text='Score 0 - 100 calculated by AI')),
                ('ai_urgency_notes', models.TextField(blank=True, help_text='Explanation of AI risk score')),
                ('status', models.CharField(choices=[('PENDING', 'Pending AI Scheduling'), ('AI_RECOMMENDED', 'AI Bundling Recommended'), ('SCHEDULED', 'Scheduled in Block Plan'), ('COMPLETED', 'Executed & Closed'), ('DEFERRED', 'Deferred to Next Horizon')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demands', to='maintenance.machineasset')),
                ('corridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_demands', to='core_rail.corridor')),
            ],
            options={
                'ordering': ['-ai_priority_score', '-criticality'],
            },
        ),
    ]
