# Generated by Django 4.0.6 on 2026-09-12 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        ('core_rail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=50, unique=True)),
                ('horizon', models.CharField(default='WEEKLY', max_length=15)),
                ('strategy', models.CharField(default='MULTI_OBJECTIVE_BALANCED', max_length=50)),
                ('total_demands_analyzed', models.IntegerField(default=0)),
                ('blocks_generated', models.IntegerField(default=0)),
                ('multi_dept_bundled_count', models.IntegerField(default=0)),
                ('synergy_rate_percentage', models.FloatField(default=0.0)),
                ('total_downtime_saved_hours', models.FloatField(default=0.0)),
                ('asset_availability_score', models.FloatField(default=98.5)),
                ('execution_time_ms', models.IntegerField(default=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorridorBlockWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('track_line', models.CharField(choices=[('UP', 'UP Line'), ('DN', 'DOWN Line'), ('BOTH', 'Both Lines')], default='UP', max_length=10)),
                ('available_duration_hours', models.FloatField(default=3.5)),
                ('train_density_score', models.IntegerField(default=15, help_text='Estimated traffic passing (lower is better)')),
                ('is_booked', models.BooleanField(default=False)),
                ('corridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_windows', to='core_rail.corridor')),
            ],
            options={
                'ordering': ['window_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ConflictAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical - Track Safety / Collision with Timetable'), ('WARNING', 'Warning - High Traffic Density Slot'), ('INFO', 'Information - Shadow Block Opportunity Available')], default='WARNING', max_length=15)),
                ('title', models.CharField(max_length=150)),
                ('details', models.TextField()),
                ('suggested_action', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_rail.corridor')),
            ],
            options={
                'ordering': ['is_resolved', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(max_length=40, unique=True)),
                ('horizon', models.CharField(choices=[('WEEKLY', 'Weekly Operational Master Schedule'), ('MONTHLY', 'Monthly Strategic Maintenance Plan')], default='WEEKLY', max_length=15)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_hours', models.FloatField(default=3.0)),
                ('track_line', models.CharField(choices=[('UP', 'UP Line'), ('DN', 'DOWN Line'), ('BOTH', 'Both Lines')], default='UP', max_length=10)),
                ('km_start', models.FloatField()),
                ('km_end', models.FloatField()),
                ('primary_department', models.CharField(choices=[('TMS', 'TMS (Track)'), ('TDMS', 'TDMS (OHE)'), ('SMMS', 'SMMS (S&T)')], max_length=10)),
                ('is_coordinated', models.BooleanField(default=False, help_text='Bundles 2+ departments simultaneously')),
                ('participating_departments', models.CharField(default='TMS', max_length=50)),
                ('estimated_downtime_saved_minutes', models.IntegerField(default=0, help_text='Downtime eliminated by bundling co-located works')),
                ('impacted_trains_count', models.IntegerField(default=0, help_text='Number of freight/passenger trains regulated in loops')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Plan'), ('AI_OPTIMIZED', 'AI Optimized & Bundled'), ('APPROVED_BY_COA', 'Approved by Chief Controller (COA)'), ('IN_PROGRESS', 'Currently In Execution'), ('COMPLETED', 'Block Completed & Track Cleared'), ('CANCELLED', 'Cancelled / Rescheduled')], default='AI_OPTIMIZED', max_length=25)),
                ('ai_optimization_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundled_demands', models.ManyToManyField(blank=True, related_name='in_block_schedules', to='maintenance.maintenancedemand')),
                ('corridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_blocks', to='core_rail.corridor')),
                ('primary_demand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_primary_block', to='maintenance.maintenancedemand')),
            ],
            options={
                'ordering': ['scheduled_date', 'start_time'],
            },
        ),
    ]
